"use client";

import { FormEvent, useEffect, useState } from "react";

const API = process.env.NEXT_PUBLIC_API_BASE_URL ?? "https://buildcost-pro-production.up.railway.app";
type Project = { id: string; code: string; name: string; status: string; description?: string | null };
type Summary = { budget_total: string; cost_total: string; income_total: string; expense_total: string; balance: string; budget_remaining: string };

async function api(path: string, options: RequestInit = {}) {
  const token = typeof window !== "undefined" ? localStorage.getItem("buildcost_access") : null;
  const headers = new Headers(options.headers); headers.set("Content-Type", "application/json");
  if (token) headers.set("Authorization", `Bearer ${token}`);
  const response = await fetch(`${API}${path}`, { ...options, headers });
  if (!response.ok) throw new Error((await response.json().catch(() => null))?.detail ?? `Request failed (${response.status})`);
  return response.status === 204 ? null : response.json();
}

function Login({ onLogin }: { onLogin: () => void }) {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState("");
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(""); try { const response = await api("/auth/login", { method: "POST", body: JSON.stringify({ email, password }) }); localStorage.setItem("buildcost_access", response.access_token); localStorage.setItem("buildcost_refresh", response.refresh_token); onLogin(); } catch (e) { setError(e instanceof Error ? e.message : "Login failed"); } };
  return <main className="page"><div className="shell"><section className="card form"><div className="brand">BuildCost Pro</div><p className="muted">Project cost management platform</p><form onSubmit={submit}><label className="field"><span>Email</span><input type="email" value={email} onChange={e => setEmail(e.target.value)} required /></label><label className="field"><span>Password</span><input type="password" value={password} onChange={e => setPassword(e.target.value)} required /></label>{error && <div className="error">{error}</div>}<button className="primary">Sign in</button></form></section></div></main>;
}

function Dashboard({ onLogout }: { onLogout: () => void }) {
  const [projects, setProjects] = useState<Project[]>([]); const [selected, setSelected] = useState<Project | null>(null); const [summary, setSummary] = useState<Summary | null>(null); const [error, setError] = useState("");
  const [projectForm, setProjectForm] = useState({ code: "", name: "" }); const [budgetForm, setBudgetForm] = useState({ name: "", amount: "" }); const [costForm, setCostForm] = useState({ category: "", quantity: "", unit_cost: "" }); const [txForm, setTxForm] = useState({ type: "EXPENSE", amount: "", description: "" });
  const load = async (preferred?: Project) => { try { const rows = await api("/api/v1/projects"); setProjects(rows); const next = preferred ?? rows[0]; if (next) await select(next); } catch (e) { setError(e instanceof Error ? e.message : "Unable to load projects"); } };
  const select = async (project: Project) => { setSelected(project); setSummary(await api(`/api/v1/projects/${project.id}/summary`)); };
  useEffect(() => { void load(); }, []);
  const submitProject = async (event: FormEvent) => { event.preventDefault(); try { const project = await api("/api/v1/projects", { method: "POST", body: JSON.stringify(projectForm) }); setProjectForm({ code: "", name: "" }); await load(project); } catch (e) { setError(e instanceof Error ? e.message : "Unable to create project"); } };
  const submitBudget = async (event: FormEvent) => { event.preventDefault(); if (!selected) return; try { await api(`/api/v1/projects/${selected.id}/budgets`, { method: "POST", body: JSON.stringify({ name: budgetForm.name, amount: budgetForm.amount }) }); setBudgetForm({ name: "", amount: "" }); await select(selected); } catch (e) { setError(e instanceof Error ? e.message : "Unable to create budget"); } };
  const submitCost = async (event: FormEvent) => { event.preventDefault(); if (!selected) return; try { await api(`/api/v1/projects/${selected.id}/costs`, { method: "POST", body: JSON.stringify({ category: costForm.category, quantity: costForm.quantity, unit_cost: costForm.unit_cost }) }); setCostForm({ category: "", quantity: "", unit_cost: "" }); await select(selected); } catch (e) { setError(e instanceof Error ? e.message : "Unable to create cost"); } };
  const submitTransaction = async (event: FormEvent) => { event.preventDefault(); if (!selected) return; try { await api(`/api/v1/projects/${selected.id}/transactions`, { method: "POST", body: JSON.stringify(txForm) }); setTxForm({ type: "EXPENSE", amount: "", description: "" }); await select(selected); } catch (e) { setError(e instanceof Error ? e.message : "Unable to create transaction"); } };
  const money = (value?: string) => value == null ? "—" : Number(value).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });
  return <main className="page"><div className="shell"><header className="header"><div><div className="brand">BuildCost Pro</div><div className="muted">Core business dashboard</div></div><button className="secondary" onClick={onLogout}>Sign out</button></header>
    {error && <div className="card error">{error}<button className="secondary" onClick={() => setError("")}>Dismiss</button></div>}
    <section className="stats"><div className="card"><div className="muted">Budget</div><div className="stat-value">{money(summary?.budget_total)}</div></div><div className="card"><div className="muted">Costs</div><div className="stat-value">{money(summary?.cost_total)}</div></div><div className="card"><div className="muted">Income</div><div className="stat-value">{money(summary?.income_total)}</div></div><div className="card"><div className="muted">Balance</div><div className="stat-value">{money(summary?.balance)}</div></div></section>
    <div className="grid"><section className="card"><h2>Projects</h2><form onSubmit={submitProject}><div className="field"><span>Code</span><input value={projectForm.code} onChange={e => setProjectForm({ ...projectForm, code: e.target.value })} required /></div><div className="field"><span>Name</span><input value={projectForm.name} onChange={e => setProjectForm({ ...projectForm, name: e.target.value })} required /></div><button className="primary">Create project</button></form><div className="list">{projects.length === 0 ? <div className="muted">No projects yet.</div> : projects.map(project => <button key={project.id} className="row" onClick={() => void select(project)}><span><strong>{project.name}</strong><br /><small className="muted">{project.code}</small></span><span className="muted">{project.status}</span></button>)}</div></section>
      <section className="card"><h2>{selected ? selected.name : "Selected project"}</h2>{selected ? <><p className="muted">{selected.description || "No description"}</p><div className="row"><span>Budget remaining</span><strong>{money(summary?.budget_remaining)}</strong></div><div className="row"><span>Expenses</span><strong>{money(summary?.expense_total)}</strong></div><h3>Add budget</h3><form onSubmit={submitBudget}><div className="field"><span>Name</span><input value={budgetForm.name} onChange={e => setBudgetForm({ ...budgetForm, name: e.target.value })} required /></div><div className="field"><span>Amount</span><input type="number" min="0" step="0.01" value={budgetForm.amount} onChange={e => setBudgetForm({ ...budgetForm, amount: e.target.value })} required /></div><button className="primary">Add budget</button></form><h3>Add cost</h3><form onSubmit={submitCost}><div className="field"><span>Category</span><input value={costForm.category} onChange={e => setCostForm({ ...costForm, category: e.target.value })} required /></div><div className="field"><span>Quantity</span><input type="number" min="0.0001" step="0.0001" value={costForm.quantity} onChange={e => setCostForm({ ...costForm, quantity: e.target.value })} required /></div><div className="field"><span>Unit cost</span><input type="number" min="0" step="0.01" value={costForm.unit_cost} onChange={e => setCostForm({ ...costForm, unit_cost: e.target.value })} required /></div><button className="primary">Add cost</button></form><h3>Add transaction</h3><form onSubmit={submitTransaction}><div className="field"><span>Type</span><select value={txForm.type} onChange={e => setTxForm({ ...txForm, type: e.target.value })}><option>INCOME</option><option>EXPENSE</option><option>ADJUSTMENT</option></select></div><div className="field"><span>Amount</span><input type="number" min="0.01" step="0.01" value={txForm.amount} onChange={e => setTxForm({ ...txForm, amount: e.target.value })} required /></div><div className="field"><span>Description</span><input value={txForm.description} onChange={e => setTxForm({ ...txForm, description: e.target.value })} /></div><button className="primary">Add transaction</button></form></> : <p className="muted">Create or select a project to begin.</p>}</section></div>
  </div></main>;
}

export default function Home() { const [authenticated, setAuthenticated] = useState(false); useEffect(() => setAuthenticated(Boolean(localStorage.getItem("buildcost_access"))), []); if (!authenticated) return <Login onLogin={() => setAuthenticated(true)} />; return <Dashboard onLogout={() => { localStorage.removeItem("buildcost_access"); localStorage.removeItem("buildcost_refresh"); setAuthenticated(false); }} />; }
